### ISSUE TITLE
Archive Repo ?

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/Iot-Telemetry-Simulator#45]
@azure Is it an archive repo ?

**Comment by gukoff** [comment]
No, why?

**Comment by ghost** [comment]
The last release was two years ago. Are there any future enhancements planned?

**Comment by gukoff** [comment]
Fair enough. We don't really update the [releases page](https://github.com/Azure-Samples/Iot-Telemetry-Simulator/releases). Because it's not obvious, I added a disclaimer (in form of a dummy release) on that page with a clarification of the process.

For each release we:
- create a new version tag in the repo: https://github.com/Azure-Samples/Iot-Telemetry-Simulator/tags. You can checkout them if you run the service from source.
- build and push a docker image with this version as a tag (and also with the "latest" tag) to `mcr.microsoft.com`. See in the README how to get and use these docker images: https://github.com/Azure-Samples/Iot-Telemetry-Simulator/blob/master/README.md?plain=1#L25

---

Regarding the future enhancements, we're open for proposals and bugfixes!

**Comment by ghost** [comment]
Nice thank you !
